[package]
name = "oc2kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdt = { version = "0.1.5", features = ["pretty-printing"] }
simple-chunk-allocator = "0.1.5"
